name: Build and upload distributions to GitHub Releases

on:
  workflow_call:
    inputs:
      tag:
        description: 'Git tag to release'
        required: true
        type: string

jobs:
  release:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checking out project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Cache Maven repository
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setting up JDK 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Building with Maven
        run: mvn -B package --file pom.xml

      - name: Upload released assets
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2
        with:
          name: ${{ inputs.tag }}
          tag_name: ${{ inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            target/dt-tool-*.*           
